### ISSUE TITLE
Peer review for project 4

### ISSUE THREAD

**Issue by pkmsoftpro** [airavata-courses/zeus#101]

**Comment by pkmsoftpro** [comment]
Hi Haritha,
I went through your kubernetes document: https://github.com/airavata-courses/zeus/wiki/Kubernetes
The steps are precise and clear. Although it will be really helpful for the kubernetes first timers if you can provide some statements that describes what the command does.

**Comment by pkmsoftpro** [comment]
The videos are nice and informative and perfectly shows the working model of your project with kubernetes and jenkins.

**Comment by pkmsoftpro** [comment]
please provide the jenkins and website credential.

**Comment by harithadamarla** [comment]
Hi Prashant,
Mailed you the creds.

**Comment by BharathaAravind** [comment]
@pkmsoftpro thanks for the feedback. We will update the commands with description

**Comment by pkmsoftpro** [comment]
I committed to your python_flask branch which triggers the jenkins build which seems to work perfectly.

**Comment by BharathaAravind** [comment]
Our Kubernetes master is on the following IP: 149.165.170.230

**Comment by pkmsoftpro** [comment]
well done guys.. able to access all the 4 services at port 30003,30009,30005,30006

**Comment by shivteja14** [comment]
Thank for your evaluating @pkmsoftpro
