### ISSUE TITLE
Milestone-4 Peer Review

### ISSUE THREAD

**Issue by aishwaryadhage** [airavata-courses/zeus#105]
Hello,
Documentation is really good. Architecture is well explained.
Also, it was a good idea to have videos for demos.
And as I had mentioned earlier, I could not see any recommendation updates after searching for a particular video, for example, I tried to search for TEDx 4-5 times.

**Comment by aishwaryadhage** [comment]
I also saw that not all the video links run, am I missing something here or it is not responding?

**Comment by aishwaryadhage** [comment]
I was just curious, are all the services and databases inside the kubernetes cluster?

**Comment by harithadamarla** [comment]
Hi Aishwarya,

You can check the change of videos in the video list upon search in our demo video as well.
[ZeusTube Website Demo](https://www.youtube.com/watch?v=EKs7HZsVyzA&feature=youtu.be)

The video may not be running,  might be because we have stored the link provided by youtube in our database. The user might have removed that video later on. 

Yeah, all services and databases are inside our Kubernetes Node

**Comment by aishwaryadhage** [comment]
Hi Haritha,
I can see the changes in video. Thanks. 
Have you guys calculated throughput after adding kubernetes?

**Comment by BharathaAravind** [comment]
> I also saw that not all the video links run, am I missing something here or it is not responding?

Some of the links are not updated. We didn't update the video links in the database.

**Comment by harithadamarla** [comment]
Hi Aishwarya,

We didn't calculate throughput after adding kubernetes with the given time.

**Comment by BharathaAravind** [comment]
> Hi Haritha,
> I can see the changes in video. Thanks.
> Have you guys calculated throughput after adding kubernetes?

We haven't compared our results before and after using JMeter. But we overcame the loading issue that you pointed in the previous peer review.

**Comment by BharathaAravind** [comment]
@aishwaryadhage the pods updated are automatically triggered when a new build is available in docker hub. Our Build and deploy is a one-step process. Once the build job is completed successfully and a new image is available in docker hub it triggers the deploy job automatically.
