### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by pkmsoftpro** [airavata-courses/zeus#37]
Hi Team Zeus,
I am assigned to review this project.
In my system python 2.7 is installed, will this work or do I need to install Python 3 as its mentioned in 
your project wiki.

Thanks.
Prashant

**Comment by BharathaAravind** [comment]
Hi @pkmsoftpro ,

The python/flask application has been tested Python3. You might face issues if you use Python 2.7. Can you please install Python 3 and set the environment variable as python3.

Thanks,
Aravind.

**Comment by pkmsoftpro** [comment]
Hi BharathaAravind,
I followed the steps as it it provided in your following wiki link:
https://github.com/airavata-courses/zeus/wiki/Assignment1

Done little changes in python_flash_ms.sh (python3 to python) in order to run it locally. 
Face an issue with mysql installation, which is resolved with the help of following links:

https://github.com/mysqljs/mysql/issues/1507
https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

Its working fine.

Thanks.
Prashant
