### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by harshallpandit** [airavata-courses/zeus#65]
Can you please send me Jenkins credentials? @ hapandit@iu.edu

**Comment by harshallpandit** [comment]
got the password. Thanks, Aravind.

**Comment by harithadamarla** [comment]
Emailed you.

**Comment by harshallpandit** [comment]
Tested CI/CD with Jenkins. Pipeline successfully completed.
Testing further.

**Comment by harshallpandit** [comment]
Can you give me RabbitMQ credentials?

**Comment by harshallpandit** [comment]
Checked jenkinsfile,  pipelines look good.
Need RabbitMQ password.

**Comment by harshallpandit** [comment]
Jenkins build runs successfully on a dummy commit.

**Comment by harshallpandit** [comment]
Summary -
front-end looks nice, all microservices works fine.
Jenkins pipeline successfully builds and deploy all microservices. 
RabbitMQ successfully responds to events.
