### ISSUE TITLE
Peer Review - Could not signup or go to home option

### ISSUE THREAD

**Issue by aishwaryadhage** [airavata-courses/zeus#66]
Hello, 
I tried to build project through jenkins and then tried to signup. 
Signup page did not work. I shows following message - 
"Cannot GET /signup"
And home page link also is not clickable.

**Comment by harithadamarla** [comment]
Hi Aishwarya,

Fixed the issue. We somehow missed the code to render the page in later commits. It's working now.

Home Page link will just redirect to our login page. (It's working you can check the same from signup page)

**Comment by aishwaryadhage** [comment]
Yes I was able to login and signup. 

I found the documentation very well written, 
After deploying through jenkins, application builds successfully and runs on the jetstream without any errors. 
I could also see rabbitmq message information in the rabbitmq overview stats.
