### ISSUE TITLE
Peer review for project 2

### ISSUE THREAD

**Issue by pkmsoftpro** [airavata-courses/zeus#68]

**Comment by pkmsoftpro** [comment]
hi team.. please send me your jenkins credential

**Comment by pkmsoftpro** [comment]
@BharathaAravind thanks for the credentials

**Comment by pkmsoftpro** [comment]
@BharathaAravind can you please check why the jenkins build is failing

**Comment by BharathaAravind** [comment]
Hi @pkmsoftpro,

I am not sure what you are looking at. I logged into Jenkins and I could see all the previous build passing. I can see that there is no build triggered today. The last two builds you can see are triggered yesterday by Aishwarya and Harshall which passed.

Please find the screenshot as reference and let me know if you are facing issue.
![jenkins build2](https://user-images.githubusercontent.com/15984286/47509212-9d674780-d843-11e8-9369-eec1d79d7a92.PNG)

**Comment by pkmsoftpro** [comment]
in the image it was build #10.

**Comment by BharathaAravind** [comment]
@pkmsoftpro .I can see the build 10 is passing

**Comment by pkmsoftpro** [comment]
![image](https://user-images.githubusercontent.com/24635859/47510321-f041fe80-d845-11e8-9618-be45f6c222f9.png)
Hi @BharathaAravind .. I have seen this message earlier.. but with build #11. . it is building successfully.

Thanks.
