### ISSUE TITLE
Project 3 Peer review

### ISSUE THREAD

**Issue by harshallpandit** [airavata-courses/zeus#70]
I see the documentation for load balancing, are you guy going to update the documentation for fault tolerance, high availability etc with their respective tests?

**Comment by harithadamarla** [comment]
Sorry for the delay. we have updated our wiki. Please check it now.

**Comment by harshallpandit** [comment]
Documentation is well written.
- checked JMeter performance results. 
- checked zookeeper structure and load balancing with zookeeper.

DId you use JMeter to check the performance of Nodejs service as well?

**Comment by BharathaAravind** [comment]
Thanks Harshall,

We haven't tested our Nodejs service Since our most work is done by Java and Python service. So we decided to do load testing on java and python services. Will do the Node JS part in the next sprint

**Comment by harshallpandit** [comment]
Ok sounds great! Checked everything written in the documentation. Closing this issue.
