### ISSUE TITLE
Peer Review - Milestone 3

### ISSUE THREAD

**Issue by aishwaryadhage** [airavata-courses/zeus#81]
Hello, 
The documentation is pretty good with the results on python and java microservices. Just, curious do you guys have multiple instances of Database?
Also, I tried to use the link provided to test zookeeper and load balancing service, it gives me static 0 or 1 value. How does this actually work, like everytime I hit the url, it increments right?

**Comment by harithadamarla** [comment]
Hi Aishwarya,

We have maintained a separate database for every microservice.

I think you have just opened the endpoints we provided. Just try logging in to the application using our ZeusTube url(http://149.165.170.230.xip.io:3001/). Just try to login the application and browse through the application and then check the endpoint they should be updated based on the number of times our instances have been used.

**Comment by aishwaryadhage** [comment]
The link keeps loading, do you think I am doing something wrong or the site can be possibly down?

**Comment by BharathaAravind** [comment]
Hi,
We checked the build. One of the peer reviews ran the Jenkins build. So, it could be the reason for it. Try running as the build is finished

**Comment by aishwaryadhage** [comment]
Yes, I think that can be the issue, I can login now.

**Comment by aishwaryadhage** [comment]
I tried to use the url to test zookeeper and load balancing service, it looks like it balances on two nodes, the results are good, I could see the change in request count. 
One thing that I observed is your application crashed after hitting search for a particular category in the search bar more than 3-4 times. 
Also, the user preferences did not work for me, it did not change the sidebar search list according to my preferences. 
One suggestion would be to have a home page button, which will redirect to the page which has list of all the videos. Once I click on a video, I could not go back to the previous home page but I could just choose from the sidebar.

**Comment by harithadamarla** [comment]
Sure thanks Aishwarya.
UserPreferences will work but app is getting crashed on increasing the load. We are able to replicate it and created an issue on this https://github.com/airavata-courses/zeus/issues/83. We will work on it on our next release.
