### ISSUE TITLE
Peer Review - Project 3

### ISSUE THREAD

**Issue by pkmsoftpro** [airavata-courses/zeus#82]

**Comment by pkmsoftpro** [comment]
Hi guys, may be because of jenkins build the server is down.. now I am able to access the login page.

Thanks @BharathaAravind

**Comment by pkmsoftpro** [comment]
I have observed one issue, once I login and if I click backward and then forward button, it allows me to log back in.. please let me know if that was an existing issue or the expected behavior. Intermittently getting the login issue, I guess I should try logging in later.

Thanks.

**Comment by harithadamarla** [comment]
It is an expected behavior because, after you login session is created, and if you click backward button followed by forward button, it shows the home page. This is because the session is still maintained. If you logout you don't see this issue.

**Comment by pkmsoftpro** [comment]
Checked the jmeter results. Checked load balancing that you guys have achieved through zookeeper.
Everything works fine. Closing the issue.

Thanks.
