### ISSUE TITLE
On multiple refreshes, zookeeper looses connection

### ISSUE THREAD

**Issue by harithadamarla** [airavata-courses/zeus#83]

**Comment by BharathaAravind** [comment]
Decided to move the implementation to kubernetes.

**Comment by harithadamarla** [comment]
Kubernetes implementation resolved this issue - (Node Microservice no more uses zookeeper to bring the nodes )
https://github.com/airavata-courses/zeus/commit/b111d142cb1a21681070d16fd83098d470fa331c
