### ISSUE TITLE
Project 4 Peer review 

### ISSUE THREAD

**Issue by harshallpandit** [airavata-courses/zeus#84]
Hi guys,
I am patiently waiting for you guys to update the wiki. Please let me know once it's done.

**Comment by harithadamarla** [comment]
Hi Harshall,

Sorry for the delay. Please access our wiki at
https://github.com/airavata-courses/zeus/wiki/Assignment-4

**Comment by harshallpandit** [comment]
I had a quick look at the documentation and watched the videos. Videos are well made and everything looks fine. 
I'll look further into it tomorrow.

**Comment by harshallpandit** [comment]
Description of microservices, CI/CD and Kubernetes is well written and easy to understand.
Checked docker hub repository, images are being tagged by Jenkins build number. 
Can you give me username and password for Jenkins and a link to front-end?

**Comment by harithadamarla** [comment]
Access our webpage at :
[ZeusTube](http://js-170-230.jetstream-cloud.org:30009/)

Mailed you the creds of Jenkins

**Comment by harshallpandit** [comment]
I committed to release branch assignment 4 but the Jenkins build didn't start.
I see that you have a webhook for docker. Did you guys remove the webhook from github?

**Comment by harithadamarla** [comment]
Hi Harshal,

Can you commit to other branches(of microservices)  ?

We have maintained a separate Jenkins for every branch of the microservice. Change made to any branch triggers the build in jenkins, pushes the docker image to hub, and pulls the latest image from the hub, and builds the pods.

**Comment by harshallpandit** [comment]
Tested Jenkins build and front-end. Works fine.
Got a new docker image on docker hub.
Can you give me IP address of your Kubernetes master?

**Comment by harshallpandit** [comment]
Oh yeah, sharing keys would be an issue. 
Screenshots look fine and I'm able to access the services from front-end after the jenkins build.

**Comment by BharathaAravind** [comment]
Thanks for the review harshall.

**Comment by harshallpandit** [comment]
Checked CI/CD, Dockerhub, frontend, jenkinsfile, dockerfile, kubernetes deployment screenshots and documentation. Everything works fine.
