### ISSUE TITLE
Code cleanup in all branches

### ISSUE THREAD

**Issue by harithadamarla** [airavata-courses/zeus#98]

**Comment by BharathaAravind** [comment]
https://github.com/airavata-courses/zeus/commit/f42a584f2a040c9e4a694e5fd66626f1f8389655

**Comment by BharathaAravind** [comment]
Cleaned dev_aravind code

**Comment by harithadamarla** [comment]
cleaned up code in node_controller branch
https://github.com/airavata-courses/zeus/commit/32d042bb44d0ca992516220091b77fdc56ac8eb7
